-- Fix identity columns: change from GENERATED ALWAYS to GENERATED BY DEFAULT
-- This resolves Drizzle ORM compatibility issue where Drizzle passes DEFAULT
-- explicitly, which PostgreSQL rejects for GENERATED ALWAYS columns
-- See: https://github.com/drizzle-team/drizzle-orm/issues/3210
ALTER TABLE "extraction_processed_connections" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "feature_tip_views" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "mcp_connection_events" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "mcp_servers" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "sms_outbound_messages" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "user_phone_numbers" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
-- Note: These columns were already dropped in migration 0033. Using IF EXISTS
-- to make this migration idempotent (snapshot chain was corrupted by branch merge).
ALTER TABLE "connections" DROP COLUMN IF EXISTS "active_stream_id";--> statement-breakpoint
ALTER TABLE "job_runs" DROP COLUMN IF EXISTS "active_stream_id";