import { test, expect } from "@playwright/test";

/**
 * E2E tests for special Next.js routes (robots.txt, sitemap.xml, manifest.webmanifest)
 *
 * These routes are generated by Next.js metadata API and must be publicly accessible
 * with correct content types.
 */

test.describe("Special Routes", () => {
    test("robots.txt is accessible", async ({ page }) => {
        const response = await page.goto("/robots.txt");

        expect(response?.status()).toBe(200);
        expect(response?.headers()["content-type"]).toContain("text");
    });

    test("robots.txt explicitly allows /connection/ for shared connections", async ({
        page,
    }) => {
        await page.goto("/robots.txt");
        const text = await page.textContent("body");

        expect(text).toContain("Allow: /connection/");
    });

    test("sitemap.xml is accessible", async ({ page }) => {
        const response = await page.goto("/sitemap.xml");

        expect(response?.status()).toBe(200);
        expect(response?.headers()["content-type"]).toContain("xml");
    });

    test("manifest.webmanifest is accessible", async ({ page }) => {
        const response = await page.goto("/manifest.webmanifest");

        expect(response?.status()).toBe(200);
        expect(response?.headers()["content-type"]).toContain("json");
    });
});
