"use client";

/**
 * Connect Header
 *
 * Dock-style navigation that mirrors the chat input at the bottom.
 * Same glass styling, same rounded corners, same shadow treatment.
 * Creates perfect visual symmetry between top and bottom of the interface.
 *
 * UX Philosophy: Harmony through reflection. The header and footer speak
 * the same visual language. Users feel the coherence without thinking about it.
 *
 * Animations:
 * - Header slides in when first connection is created
 * - Title smoothly transitions when generated by LLM
 * - Search dropdown animates in with spring-like motion
 */

import { useState, useRef, useEffect, useCallback, useMemo } from "react";
import Image from "next/image";
import Link from "next/link";
import { Plus, Search, X, Clock, Loader2, Sparkles } from "lucide-react";

import { cn } from "@/lib/utils";
import { OptionalUserButton } from "@/components/connection/optional-user-button";
import { useConnection } from "./connection-context";

/** Formats a date as relative time (e.g., "2h ago", "Yesterday") */
function getRelativeTime(date: Date | null): string {
    if (!date) return "";

    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

    if (diffMins < 1) return "Just now";
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays === 1) return "Yesterday";
    if (diffDays < 7) return `${diffDays}d ago`;

    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

/** Animated indicator for running connections */
function RunningIndicator() {
    return (
        <div className="flex items-center gap-1">
            <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary/60 opacity-75" />
                <span className="relative inline-flex h-2 w-2 rounded-full bg-primary" />
            </span>
        </div>
    );
}

/**
 * Animated title component that smoothly transitions between titles.
 * Uses CSS transitions with a key change for smooth crossfade.
 */
function AnimatedTitle({ title }: { title: string }) {
    return (
        <span
            key={title} // Key change triggers remount with animation
            className={cn(
                "truncate text-sm text-foreground/70",
                "duration-300 animate-in fade-in slide-in-from-bottom-1"
            )}
        >
            {title}
        </span>
    );
}

export function ConnectHeader() {
    const {
        connections,
        activeConnection,
        runningCount,
        setActiveConnection,
        createNewConnection,
        isPending,
        isLoaded,
    } = useConnection();

    const [isSearchOpen, setIsSearchOpen] = useState(false);
    const [query, setQuery] = useState("");
    const inputRef = useRef<HTMLInputElement>(null);

    // Track if we've ever shown the header (for entrance animation)
    const [hasShownHeader, setHasShownHeader] = useState(false);

    // Header should be visible when we have an active connection
    const shouldShowHeader = isLoaded && activeConnection !== null;

    // Track header visibility for entrance animation
    useEffect(() => {
        if (shouldShowHeader && !hasShownHeader) {
            // Small delay to ensure CSS transition works
            const timer = setTimeout(() => setHasShownHeader(true), 50);
            return () => clearTimeout(timer);
        }
    }, [shouldShowHeader, hasShownHeader]);

    const closeSearch = useCallback(() => {
        setIsSearchOpen(false);
        setQuery("");
    }, []);

    const openSearch = useCallback(() => setIsSearchOpen(true), []);

    const handleSelect = useCallback(
        (id: string) => {
            setActiveConnection(id);
            closeSearch();
        },
        [setActiveConnection, closeSearch]
    );

    // Focus input when search opens
    useEffect(() => {
        if (isSearchOpen && inputRef.current) {
            inputRef.current.focus();
        }
    }, [isSearchOpen]);

    // Handle ESC key to close search
    useEffect(() => {
        const handleEscape = (e: KeyboardEvent) => {
            if (e.key === "Escape" && isSearchOpen) {
                closeSearch();
            }
        };
        window.addEventListener("keydown", handleEscape);
        return () => window.removeEventListener("keydown", handleEscape);
    }, [isSearchOpen, closeSearch]);

    // Filter connections based on search query
    const filtered = useMemo(() => {
        if (!query.trim()) {
            return connections.slice(0, 6);
        }

        const lowerQuery = query.toLowerCase();
        return connections.filter(
            (c) =>
                c.title?.toLowerCase().includes(lowerQuery) ||
                c.id.toLowerCase().includes(lowerQuery)
        );
    }, [connections, query]);

    // Display title or placeholder
    const displayTitle = activeConnection?.title || "New connection";

    // Don't render until we should show the header
    if (!shouldShowHeader) {
        return null;
    }

    return (
        <header
            className={cn(
                "flex items-center justify-between px-4 py-3 sm:px-6",
                "transition-all duration-500 ease-out",
                // Entrance animation
                hasShownHeader
                    ? "translate-y-0 opacity-100"
                    : "-translate-y-4 opacity-0"
            )}
        >
            {/* Logo */}
            <Link
                href="/"
                className="flex shrink-0 items-center gap-2 transition-opacity hover:opacity-80"
            >
                <Image
                    src="/logos/icon-transparent.png"
                    alt="Carmenta"
                    width={36}
                    height={36}
                    className="h-9 w-9"
                    priority
                />
                <span className="hidden text-lg font-semibold tracking-tight text-foreground/90 lg:inline">
                    Carmenta
                </span>
            </Link>

            {/* Center: Dock style - mirrors chat input */}
            <div className="relative">
                <div
                    className={cn(
                        "glass-input-dock flex min-w-[280px] items-center gap-2 sm:min-w-[400px]",
                        "transition-all duration-500 ease-out",
                        hasShownHeader ? "scale-100 opacity-100" : "scale-95 opacity-0"
                    )}
                >
                    {/* Search button */}
                    <button
                        onClick={openSearch}
                        className={cn(
                            "flex h-9 w-9 shrink-0 items-center justify-center rounded-full",
                            "text-foreground/40 hover:bg-white/40 hover:text-foreground/60",
                            "transition-all"
                        )}
                        title="Search connections"
                    >
                        <Search className="h-4 w-4" />
                    </button>

                    {/* Title - opens search */}
                    <button
                        onClick={openSearch}
                        className="flex min-w-0 flex-1 items-center gap-2 py-1"
                    >
                        {runningCount > 0 && <RunningIndicator />}
                        <AnimatedTitle title={displayTitle} />
                    </button>

                    {/* New chat button - like send button */}
                    <button
                        onClick={createNewConnection}
                        disabled={isPending}
                        className={cn(
                            "flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition-all",
                            "bg-gradient-to-br from-[rgba(200,160,220,0.8)] via-[rgba(160,200,220,0.8)] to-[rgba(220,180,200,0.8)]",
                            "text-white/90 hover:scale-105 hover:shadow-md",
                            "disabled:opacity-50 disabled:hover:scale-100"
                        )}
                        title="New connection"
                    >
                        {isPending ? (
                            <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                            <Plus className="h-4 w-4" />
                        )}
                    </button>
                </div>

                {/* Search dropdown - positioned below */}
                {isSearchOpen && (
                    <>
                        <div className="fixed inset-0 z-40" onClick={closeSearch} />
                        <div
                            className={cn(
                                "absolute left-0 right-0 top-full z-50 mt-2",
                                "duration-200 animate-in fade-in slide-in-from-top-2"
                            )}
                        >
                            <div className="overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-foreground/10">
                                {/* Search input header with close button */}
                                <div className="flex items-center gap-3 border-b border-foreground/10 px-4 py-3">
                                    <Search className="h-5 w-5 text-foreground/40" />
                                    <input
                                        ref={inputRef}
                                        type="text"
                                        value={query}
                                        onChange={(e) => setQuery(e.target.value)}
                                        placeholder="Search connections..."
                                        className="flex-1 bg-transparent text-base text-foreground/90 outline-none placeholder:text-foreground/40"
                                    />
                                    <button
                                        onClick={closeSearch}
                                        className="rounded-full p-1 transition-colors hover:bg-foreground/5"
                                        title="Close"
                                        aria-label="Close search"
                                    >
                                        <X className="h-4 w-4 text-foreground/40" />
                                    </button>
                                </div>

                                {/* Results list */}
                                <div className="max-h-80 overflow-y-auto">
                                    <div className="flex items-center gap-2 bg-foreground/5 px-4 py-2">
                                        <Clock className="h-3.5 w-3.5 text-foreground/40" />
                                        <span className="text-xs font-medium uppercase tracking-wider text-foreground/50">
                                            {query ? "Results" : "Recent"}
                                        </span>
                                    </div>
                                    {filtered.length > 0 ? (
                                        <div className="py-2">
                                            {filtered.map((conn, index) => (
                                                <button
                                                    key={conn.id}
                                                    onClick={() =>
                                                        handleSelect(conn.id)
                                                    }
                                                    className={cn(
                                                        "flex w-full items-start gap-3 px-4 py-2.5 text-left transition-colors hover:bg-foreground/5",
                                                        conn.id ===
                                                            activeConnection?.id &&
                                                            "bg-primary/5",
                                                        // Staggered animation for list items
                                                        "animate-in fade-in slide-in-from-left-2"
                                                    )}
                                                    style={{
                                                        animationDelay: `${index * 30}ms`,
                                                        animationFillMode: "backwards",
                                                    }}
                                                >
                                                    <div className="mt-0.5">
                                                        {conn.streamingStatus ===
                                                        "streaming" ? (
                                                            <Loader2 className="h-4 w-4 animate-spin text-primary" />
                                                        ) : (
                                                            <Sparkles className="h-4 w-4 text-foreground/40" />
                                                        )}
                                                    </div>
                                                    <div className="min-w-0 flex-1">
                                                        <div className="flex items-center gap-2">
                                                            <span className="truncate text-sm font-medium text-foreground/80">
                                                                {conn.title ||
                                                                    "New connection"}
                                                            </span>
                                                        </div>
                                                        <div className="mt-0.5 flex items-center gap-2">
                                                            <span className="shrink-0 text-xs text-foreground/30">
                                                                {getRelativeTime(
                                                                    conn.lastActivityAt
                                                                )}
                                                            </span>
                                                        </div>
                                                    </div>
                                                </button>
                                            ))}
                                        </div>
                                    ) : (
                                        <div className="py-8 text-center text-sm text-foreground/50">
                                            {connections.length === 0
                                                ? "We haven't started any connections yet"
                                                : "We couldn't find any matching connections"}
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    </>
                )}
            </div>

            {/* Right side - just user button */}
            <div className="flex shrink-0 items-center gap-3">
                <OptionalUserButton />
            </div>
        </header>
    );
}
